### PR TITLE
(#159) fixed hashcode function in bitArray

### PR DESCRIPTION
**Pull request by AnderWoche**
We need a Open-ended range

https://kotlinlang.org/docs/ranges.html
```kotlin
// Closed-ended range
println(4 in 1..4)
// true

// Open-ended range
println(4 in 1..<4)
// false
```

### CODE REVIEW

**Comment by AnderWoche** [comment]
I need a snapshot! to continue working!

**Comment by Quillraven** [comment]
Thanks for the PR although I am not 100% sure if the open ended range is correct.

Can you update the test cases to check typical edge cases?

Empty BitArray, first bit last, last bit set, first bit of an additional long set, last bit of an additional long set. Something like that.

You can build Fleks locally. Just execute the publishToMavenLocal task or whatever it is called.

I try to find some time in the evening to have a more detailed look into the issue. If everything looks good I can merge the PR. But I don't want to blindly merge stuff without having a look first.

**Comment by Quillraven** [comment]
@AnderWoche: I had a more detailed look now and while your change will definitely fix the issue, I think it is not the best solution. Why?

The loop is then actually not entered for the first 63 bits of the BitArray resulting in the same hashcode for all of them.

I then also compared once more with the code of LibGDX's Bits class where I think I took the code from. This class actually also crashes in the same scenario :D So it is already broken in LibGDX.

I then checked some different hashCode implementations of other fast BitSet collections in other languages and just replaced the current with a new one.

Also, enhanced the test with some additional test cases and seems good. Please try it out and let me know if it works for you as well!

Good catch and thank you for the help on pointing down the issue!

**Comment by tommyettinger** [comment]
This is a pretty thorny issue, there's a lot of ways something like this can go wrong. `Bits` in libGDX currently (in 1.13.0) can also throw an ArrayIndexOutOfBoundsException in similar cases, I think the code is similar in other places too. I've been experimenting with fixes in [my digital repo](https://github.com/tommyettinger/digital/blob/main/src/test/java/com/badlogic/gdx/utils2/Bits.java#L318-L325); I think this highlighted range should work. The `length() + 63 >>> 6` effectively gets 1/64 of length() rounded up. If the only bit is set with `set(63)`, then that evaluates to 1, and since we use an exclusive range here, then this only hashes bits 0-63, correctly (only long item 0). If we had instead used `set(64)`, then that evaluates to 2, and so this will try to hash what it can of bits 0-127 (long items 0 and 1). If you want me to port that to Kotlin I can, but it should be fairly close to what you already have, just with a different calculation using `length()`, and an exclusive range in the loop.

**Pull request closed without merging**
